services:
  arm-builder:
    platform: linux/arm/v7  # change to "linux/arm64" when building for Raspberry Pi 3 and newer (64-bit, 2016)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arm-nuitka
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
